### PR TITLE
Fix conflicting key bindings with evil-org

### LINKED ISSUE #8: Conflicting key bindings with evil-org
Thanks for the great package. Org-mode supports LaTeX too so it makes sense to enable this in org-mode, but org-mode and [evil-org](https://github.com/Somelauw/evil-org-mode) has some conflicting key bindings with this package: `[[`, `]]`, `vie` and `vae`.

The evil-tex `[[` and `]]` don't really make sense in org-mode so the org-mode ones can take priority in org-mode.

In evil-org `vie` and `vae` mean the surrounding org-mode element, like a table cell or entire code block, while in evil-tex they mean the LaTeX environment block. I think it makes sense to use the evil-tex functions when in a LaTeX environment and fallback to the the evil-org functions otherwise.

I have the following workaround in my init.el but it would be nice to have this resolved upstream. Would you consider a pull request for this here?

```elisp
      (evil-define-text-object evil-tex-inner-env-or-evil-org-inner-object (count &optional beg end type)
        "Default to `evil-tex-inner-env' and fallback on `evil-org-inner-object'."
        (condition-case nil (evil-tex-inner-env count beg end type)
          (error (when (eq major-mode 'org-mode)
                   (evil-org-inner-object count beg end type)))))
      (evil-define-text-object evil-tex-an-env-or-evil-org-an-object (count &optional beg end type)
        "Default to `evil-tex-an-env' and fallback on `evil-org-an-object'."
        (condition-case nil (evil-tex-an-env count beg end type)
          (error (when (eq major-mode 'org-mode)
                   (evil-org-an-object count beg end type)))))
      (defun evil-tex-go-back-section-or-org-previous-visible-heading (&optional arg)
        (interactive)
        (if (eq major-mode 'org-mode)
            (org-previous-visible-heading (or arg 1))
          (evil-tex-go-back-section arg)))
      (defun evil-tex-go-forward-section-or-org-next-visible-heading (&optional arg)
        (interactive)
        (if (eq major-mode 'org-mode)
            (org-next-visible-heading (or arg 1))
          (evil-tex-go-forward-section arg)))
      (defun setup-evil-tex-binding-replacements ()
        (evil-define-key* '(normal motion) evil-tex-mode-map
          [remap evil-tex-go-back-section] 'evil-tex-go-back-section-or-org-previous-visible-heading
          [remap evil-tex-go-forward-section] 'evil-tex-go-forward-section-or-org-next-visible-heading)
        (evil-define-key '(visual operator) 'evil-tex-mode-map
          [remap evil-tex-inner-env] 'evil-tex-inner-env-or-evil-org-inner-object
          [remap evil-tex-an-env] 'evil-tex-an-env-or-evil-org-an-object))
      (add-hook 'evil-tex-mode-hook 'setup-evil-tex-binding-replacements nil 'local)
```

### PR DESCRIPTION
**Pull request by rolag**
Fixes #8.

### CODE REVIEW

**Comment by ymarco** [comment]
Thanks for the PR!

I'd rather have evil-tex-go-{back,forward}-section fall back on the usual evil/org keybinds than have this new keymap evil-tex-mode-org-mode-map.
Is that possible?

**Comment by rolag** [comment]
So the problem with that I think is that evil-tex-mode-map is a minor mode map which overrides the bindings in the org-mode major mode map. Minor mode maps appear to be "global" and the way to have different minor mode mappings per major-mode is to use minor-mode-overriding-map-alist.

**Comment by rolag** [comment]
Never mind, I think I misunderstood what you meant by fall back. I can put a conditional in the evil-tex-go-{back,forward}-section for org-mode if that's what you mean.

**Comment by ymarco** [comment]
I thought we could have evil-tex-go-{back,forward}-section call the normal evil-{backward,forward}-section-begin functions when in org-mode.

It might be annoying for people who want custom keybinds for [[  ]] in org but evil-tex's [[ ]] binds in LaTeX. But I think it's a rare enough case and they can advise evil-tex for that anyway.

**Pull request closed without merging**
